apiVersion: v1
kind: Namespace
metadata:
  name: tts
---
apiVersion: v1
kind: Service
metadata:
  name: tts-login
  namespace: tts
spec:
  selector:
    app: tts-login
  type: LoadBalancer
  ports:
  - name: tts-login
    protocol: TCP
    port: 80
    targetPort: 1323
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  tts-login
  namespace: tts
  labels:
    app:  tts-login
spec:
  selector:
    matchLabels:
      app: tts-login
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  tts-login
    spec:
      containers:
      - name:  tts-login
        image:  fightingsj/demo:tts-login
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: TTS_APP_KEY
          value: xxxx
        - name: TTS_APP_SECRET
          value: xxxx
        ports:
        - containerPort: 1323
          name:  http
      restartPolicy: Always